name: Rubric Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        python-version: [3.7, 3.8, 3.9]

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install the Dependencies
        run: |
          echo "Upgrading pip ...."
          python -m pip install --upgrade pip
          echo "Installing the dependencies..."
          python3 -m venv .venv
          source .venv/bin/activate
          pip install -r requiements.txt && pip install -r requirements-dev.txt

      - name: Check Linter
        run: |
          echo "Checking linter formatting..."
          black --check .
          isort --check .
          mypy .
          flake8 .

      - name: Run Tests
        run: |
          echo "Running the tests..."
          pytest tests
