name: Rubric Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  ci:
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.7, 3.8, 3.9]
        poetry-version: [1.1.7]
        os: [ubuntu-latest, macos-latest]

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Run image
        uses: abatilo/actions-poetry@v2.0.0
        with:
          poetry-version: ${{ matrix.poetry-version }}

      - name: Install the Dependencies
        run: |
          echo "Installing the dependencies..."
          poetry install

      - name: Check Linter
        run: |
          echo "Checking linter formatting..."
          poetry run black --check .
          poetry run isort --check .
          poetry run flake8 .
          poetry run pip install types-setuptools
          poetry run pip install types-pkg_resources
          poetry run mypy . --install-types

      - name: Run Tests
        run: |
          echo "Running the tests..."
          poetry run pytest tests
