name: Rubric Test

on:
  push:
    branches:
      - main
      - dev

  pull_request:
    branches:
      - main

  schedule:
    # Run cron at the end of every day.
    - cron: "0 0 * * *"

jobs:
  ci:
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.8", "3.9", "3.10"]
        os: [ubuntu-latest, macos-latest]

    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
          # NOTE: Cache server bug
          # https://github.com/actions/setup-node/issues/379

          # cache: "pip"
          # cache-dependency-path: |
          #   ./requirements.txt
          #   ./requirements-dev.txt

      - name: Install the Dependencies
        run: |
          echo "Installing the dependencies..."
          python -m pip install -r requirements-dev.txt

      - name: Check Linter
        run: |
          echo "Checking linter formatting..."
          make lint-check

      - name: Run Tests
        run: |
          echo "Running the tests..."
          python -m pytest
